#ifndef SCRIPTREADER_GLOBAL_H
#define SCRIPTREADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCRIPTREADER_LIBRARY)
#  define SCRIPTREADERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SCRIPTREADERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SCRIPTREADER_GLOBAL_H
